

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
 * Author: Lucy Vass
 * GUI code generated using NetBeans IDE 8.2 and edited in Eclipse
 */

public class StartPageGUI extends javax.swing.JFrame implements ActionListener {

	private static final long serialVersionUID = 1L; //creating a serial number as JDialog is a serialisable class

    public StartPageGUI() {
        initComponents(); //calling the constructor to create the components
    }
                      
    private void initComponents() { //constructor which creates components of the JFrame 
    	
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        
        newFilename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buildButton = new javax.swing.JButton();
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); //closes the window
        
        //Setting the text for the JTextFields
        jMenuItem2.setText("jMenuItem2");
        jLabel1.setText("Welcome to Network Builder");
        jLabel2.setText("Create a new network");
        newFilename.setText("File name");
        jLabel4.setText("Enter file path:");
        buildButton.setText("Build");
        
      //Adding ActionListeners for all interactive parts of the JFrame -ie buttons
        
        

        buildButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildButtonActionPerformed(evt);
            }
        });

        //Layout - code generated by NetBeans IDE 8.2
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buildButton)
                            )))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(buildButton))
                .addGap(23, 23, 23)
                
                .addGap(14, 14, 14)
                
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }                                       

    private void buildButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Creating a new network
    	String inputfile = newFilename.getText();
    	int len = inputfile.length();
    	String extension = new StringBuilder().append(inputfile.charAt(len-4)).append(inputfile.charAt(len-3)).append(inputfile.charAt(len-2)).append(inputfile.charAt(len-1)).toString();
    	//preventing the user entering a file without a .txt extension as this will prevent proper naming, produces error pop-up
    	if (! extension.equals(".txt")){
    		JOptionPane.showMessageDialog(null, "File must have extension .txt", "InfoBox: " + "Error", JOptionPane.INFORMATION_MESSAGE);
	    	}
    	try {
			//creating a new JDialog for the network
    		Network myNetwork = new Network(inputfile);
			JDialog newpage = new NetworkViewGUI(null, rootPaneCheckingEnabled, myNetwork);
			newpage.setVisible(true);
		} catch (IOException e) {
			//catches the IOException if the file cannot be found, produces error pop-up
			JOptionPane.showMessageDialog(null, "Can't find file", "InfoBox: " + "Error", JOptionPane.INFORMATION_MESSAGE);
		}
    	
    }                                                 

    
    public static void main(String args[]) {
        //Setting the 'Nimbus' look and feel - code generated by Netbeans IDE 8.2
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPageGUI().setVisible(true);
            }
        });
    }

 // Variables declaration                    
    private javax.swing.JButton buildButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField newFilename;
    // End of variables declaration                   

	@Override
	public void actionPerformed(ActionEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	

	
}
